#Docker-Compose para o projeto Point-System
version: '3.7'

services:
  db:
    image: postgres:11
    restart: always
    ports:
      - '5432:5432'

    volumes:
      - 'postgres_data:/data'
      - './sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql'

    environment:
      POSTGRES_DB: system_point
      POSTGRES_PASSWORD: 123456

  redis:
    image: redis
    command: redis-server --requiredpass Redis2021!
    ports:
      - '6379:6379'


volumes:
  postgres_data: {}
