#Docker-Compose para o projeto Point-System
version: '3.7'

services:
  db:
    image: postgres:11
    restart: always
    ports:
      - '5432:5432'

    volumes:
      - 'postgres_data:/data'
      - './sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql'

    environment:
      POSTGRES_DB: system_point
      POSTGRES_PASSWORD: 123456

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    #command: redis-server --requirepass Redis2021!

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - ALLOW_EMPTY_PASSWORD:yes
      - REDIS_HOSTS=local:redis:6379

    ports:
      - '8081:8081'

    depends_on:
      - redis

volumes:
  postgres_data: {}
